name: Generate Snake Animation

on:
  schedule:
    # Run daily
    - cron: "0 0 * * *"
  workflow_dispatch:

jobs:
  generate:
    runs-on: ubuntu-latest
    steps:
      # Pulls the GitHub Contribution Snake generator
      - name: Generate Snake Animation
        uses: Platane/snk@v2
        with:
          github_user_name: Sujith-Kumar-2003
          outputs: dist/snake.svg

      # Push the generated Snake Animation to your repository
      - name: Push Snake to Repository
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: dist
