name: Generate Snake Animation

on:
  schedule:
    - cron: "0 0 * * *"  # Run daily
  workflow_dispatch:  # Allow manual triggers

jobs:
  generate:
    runs-on: ubuntu-latest
    permissions:
      contents: write  # Allow pushing changes
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v3

      - name: Generate Snake Animation
        uses: Platane/snk@v3.0.0
        with:
          github_user_name: Sujith-Kumar-2003
          outputs: dist/snake.svg

      - name: Push Snake to Repository
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_branch: output
          publish_dir: dist
